BOW YÖNTEMİ

In [2]:
from sklearn.feature_extraction.text import CountVectorizer 

In [3]:
import pandas as pd

In [4]:
import on_islem

In [5]:
df=pd.read_csv("data/nlp.csv",index_col=0)

In [8]:
df["Text_2"]=df["Text"].apply(on_islem.pre_processing)
df["Text_2"]=df["Text_2"].apply(on_islem.remove_space)

In [9]:
#bos liste kontrolü
df[df["Text_2"].str[0].isnull()]

Text Text_2
194  #hesaplamalısosyalbilimler #computationalsocia...     []
464  #investment #software #technology #tech #innov...     []

In [10]:
df_index= df[df["Text_2"].str[0].isnull()].index
df=df.drop(df_index)
df=df.reset_index()
del df["index"]
df[df["Text_2"].str[0].isnull()]
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  
1  [veri, analiz, edin, chatgptyi, kullanarak, do...  
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...  
3  [baidu, research, çin, ön, gele, ara, motor, b...  
4  [microsoft, ai, microsoft, yapay, zeka, teknol...

In [11]:
df["Text_2"]

0      [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...
1      [veri, analiz, edin, chatgptyi, kullanarak, do...
2      [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...
3      [baidu, research, çin, ön, gele, ara, motor, b...
4      [microsoft, ai, microsoft, yapay, zeka, teknol...
                             ...                        
851    [doğal, dil, işle, alan, yük, lisansdoktor, ya...
852                              [dogal, dil, isle, şey]
853    [bir, ver, madencilik, ve, doğal, dil, işle, u...
854    [doğal, dil, işleme, il, ilgil, deney, ola, ya...
855    [hafta, öğrencilik, hayat, kaldık, yer, deva, ...
Name: Text_2, Length: 856, dtype: object

In [12]:
df["Text_3"]=[' '.join(w for w in item) for item in df["Text_2"]]
df

Text   
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
851  doğal dil işleme alanında yüksek lisans-doktor...   
852                           dogal dil isleme şeyleri   
853  Bir veri madenciliği ve doğal dil işleme uygul...   
854  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
855  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2   
0    [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  \
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
851  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
852                            [dogal, dil, isle, şey]   
853  [bir, ver, madencilik, ve, doğal, dil, işle, u...   
854  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
855  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3  
0    yapay zeka nedir ne işe yarar yapay zeka yz bi...  
1    veri analiz edin chatgptyi kullanarak doğal di...  
2    öncelik yapay zeka ne olduğunu iç ne önemli ol...  
3    baidu research çin ön gele ara motor baidun ar...  
4    microsoft ai microsoft yapay zeka teknoloji od...  
..                                                 ...  
851  doğal dil işle alan yük lisansdoktor yapa danı...  
852                                 dogal dil isle şey  
853     bir ver madencilik ve doğal dil işle uygulamas  
854  doğal dil işleme il ilgil deney ola yazılımcı ...  
855  hafta öğrencilik hayat kaldık yer deva ediyoru...  

[856 rows x 3 columns]

In [13]:
vectorizer=CountVectorizer()
X=vectorizer.fit_transform(df["Text_3"].tolist())
X

<856x4816 sparse matrix of type '<class 'numpy.int64'>'
	with 18512 stored elements in Compressed Sparse Row format>

In [14]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [15]:
X[0]


<1x4816 sparse matrix of type '<class 'numpy.int64'>'
	with 31 stored elements in Compressed Sparse Row format>

In [16]:
df["Text_4"]=X.toarray().tolist()
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir ne işe yarar yapay zeka yz bi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4  
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

TF-IDF

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["Text_3"].tolist())


In [29]:
print(X.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [30]:
set(X.toarray()[0])

{0.0,
 0.034529070849074917,
 0.03622575493051819,
 0.06380954274919588,
 0.11306928983235955,
 0.12113530293154322,
 0.12593707722050587,
 0.12725540952048855,
 0.1468953954470458,
 0.15077680730861912,
 0.15217931312202868,
 0.15364417262024727,
 0.16413846903940033,
 0.17098099851648932,
 0.17361871890860822,
 0.18698038063938943,
 0.19646063050859733,
 0.20242314449413515,
 0.20982229223937857,
 0.21869940280667285,
 0.21930254210858646,
 0.23266420383936767,
 0.31105993894123957}

In [31]:
df["Text_5"] = X.toarray().tolist()
df

Text   
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
851  doğal dil işleme alanında yüksek lisans-doktor...   
852                           dogal dil isleme şeyleri   
853  Bir veri madenciliği ve doğal dil işleme uygul...   
854  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
855  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2   
0    [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  \
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
851  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
852                            [dogal, dil, isle, şey]   
853  [bir, ver, madencilik, ve, doğal, dil, işle, u...   
854  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
855  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3   
0    yapay zeka nedir ne işe yarar yapay zeka yz bi...  \
1    veri analiz edin chatgptyi kullanarak doğal di...   
2    öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3    baidu research çin ön gele ara motor baidun ar...   
4    microsoft ai microsoft yapay zeka teknoloji od...   
..                                                 ...   
851  doğal dil işle alan yük lisansdoktor yapa danı...   
852                                 dogal dil isle şey   
853     bir ver madencilik ve doğal dil işle uygulamas   
854  doğal dil işleme il ilgil deney ola yazılımcı ...   
855  hafta öğrencilik hayat kaldık yer deva ediyoru...   

                                                Text_4   
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
..                                                 ...   
851  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
852  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
853  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
854  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
855  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                                Text_5  
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..                                                 ...  
851  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
852  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
853  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
854  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
855  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[856 rows x 5 columns]

In [32]:
len(X.toarray()[0])

4816

#word2vec

In [42]:
from gensim.models import Word2Vec


In [40]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir ne işe yarar yapay zeka yz bi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [43]:
model = Word2Vec(sentences=df["Text_2"].tolist(), vector_size=100, window=5, min_count=1)
model.save("data/word2vec.model")

In [44]:
print(model)

Word2Vec<vocab=4827, vector_size=100, alpha=0.025>


In [45]:
words=list(model.wv.index_to_key)
words[0:6]

['dil', 'doğal', 'işle', 've', 'bir', 'yapay']

In [46]:
len(words)

4827

In [47]:
df

Text   
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
851  doğal dil işleme alanında yüksek lisans-doktor...   
852                           dogal dil isleme şeyleri   
853  Bir veri madenciliği ve doğal dil işleme uygul...   
854  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
855  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2   
0    [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  \
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
851  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
852                            [dogal, dil, isle, şey]   
853  [bir, ver, madencilik, ve, doğal, dil, işle, u...   
854  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
855  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3   
0    yapay zeka nedir ne işe yarar yapay zeka yz bi...  \
1    veri analiz edin chatgptyi kullanarak doğal di...   
2    öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3    baidu research çin ön gele ara motor baidun ar...   
4    microsoft ai microsoft yapay zeka teknoloji od...   
..                                                 ...   
851  doğal dil işle alan yük lisansdoktor yapa danı...   
852                                 dogal dil isle şey   
853     bir ver madencilik ve doğal dil işle uygulamas   
854  doğal dil işleme il ilgil deney ola yazılımcı ...   
855  hafta öğrencilik hayat kaldık yer deva ediyoru...   

                                                Text_4   
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
..                                                 ...   
851  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
852  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
853  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
854  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
855  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                                Text_5  
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..                                                 ...  
851  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
852  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
853  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
854  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
855  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[856 rows x 5 columns]

In [48]:
model.wv.key_to_index["yapay"] #kelimelerimizi vektör haline getirdik

5

In [49]:
model.wv[5]

array([-0.16821606,  0.27742228,  0.06201028, -0.0035947 , -0.02686713,
       -0.38071355,  0.09646613,  0.6126135 , -0.18631572, -0.25841233,
       -0.12354308, -0.48490465, -0.05664507,  0.18419492,  0.0579827 ,
       -0.17793867,  0.13379954, -0.33073488, -0.03177415, -0.6607954 ,
        0.2270336 ,  0.19060688,  0.3705023 , -0.03768836,  0.01547902,
        0.17061384, -0.17135498, -0.14728676, -0.23906462,  0.04327727,
        0.41821942, -0.03053239,  0.05647695, -0.36061525, -0.025004  ,
        0.36516762,  0.09669809, -0.01932287, -0.19401047, -0.29723904,
        0.20090441, -0.20350385, -0.21645947, -0.06165057,  0.18552513,
       -0.23156409, -0.18486348, -0.01401694,  0.12352695,  0.06079786,
        0.13619645, -0.19432335, -0.06232665, -0.02408809, -0.11965702,
        0.13724123,  0.17633238, -0.02128966, -0.32084054, -0.07431126,
        0.04501867,  0.05315821,  0.09605782,  0.03239287, -0.31271735,
        0.30582923,  0.04474587,  0.22933118, -0.27782357,  0.27

In [52]:
def word2vec(value):
    model = Word2Vec.load("data/word2vec.model")
    bfr_list = []
    bfr_len = len(value)
    
    for k in value:
        bfr = model.wv.key_to_index[k]
        bfr = model.wv[bfr]
        bfr_list.append(bfr)
        
    bfr_list = sum(bfr_list)
    bfr_list = bfr_list/bfr_len
    return bfr_list.tolist()

In [53]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir ne işe yarar yapay zeka yz bi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [ ]:
df["Text_6"] = df["Text_2"].apply(word2vec)

In [57]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir ne işe yarar yapay zeka yz bi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5   
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  \
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                              Text_6  
0  [-0.08587712794542313, 0.14841297268867493, 0....  
1  [-0.06346157938241959, 0.1158541664481163, 0.0...  
2  [-0.08179476112127304, 0.14106719195842743, 0....  
3  [-0.07533200830221176, 0.13017775118350983, 0....  
4  [-0.10259126871824265, 0.17812003195285797, 0....